# Site Info
title: WJ's blog
tagline: '변화를 위한 첫걸음'
description: 'blog for change'
url: https://woojin1223.github.io/
logo: '/public/img/favicon/favicon.ico'

# Site configurations
plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'base16.solarized'
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Woo Jin
  description: <strong>Data Scientist</strong>, Woo Jin.
  gravatar: 8b9b5b0f787c7b89e9914c86cfb26257 # md5 hash of your email address
  contact:
    # linkedin:  <hide>
    github: https://github.com/woojin1223
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    email: mailto:ahnwj2004@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/blog/'
    - Categories: '/blog/categories/'
    - Tags: '/blog/tags/'
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: '/public/img/yosigo.jpg'
  caption: Photograph by YOSIGO.

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'G-7BD8CT32B0' # leave blank if you don't want google analytics
# disqus_short_name: #  # leave blank if you don't want disqus

# comments:
  # provider    : # "disqus"                                # comment 처리 사이트 명칭 기재
              # false (default), "disqus", "discourse", "facebook"
              # "staticman", "staticman_v2", "utterances", "custom"
  # disqus:
    # shortname : # "greeksharifa-github-io"                    # disqus의 shortname 기재