# Site Info
title: Ahn Woo Jin
tagline: "변화를 위한 첫걸음"
description: "powered by jekyll"
baseurl: ""
url: https://woojin1223.github.io
logo: # '/public/img/logo.webp'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'base16.solarized'
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/contents/page:num'
permalink: pretty
# permalink: /:title/

version: 1.0.0

# About/contact
author:
  name: Ahn Woo Jin
  description: <strong>Data Scientist</strong>, Woo Jin.
  gravatar: # 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    # linkedin:  <hide>
    github: https://github.com/woojin1223
    # facebook:  <hide>
    # twitter:   <hide>
    # weibo:     <hide>
    email: mailto:ahnwj2004@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Contents:
    - '/contents/'
    - {Categories: '/contents/categories/'}
    - {Tags: '/contents/tags/'}
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/contents/tags/'
category_page: '/contents/categories/'

hero:
  image: /public/img/yosigo.jpg
  caption: Photograph by YOSIGO.

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: # 'G-XEE6P4YHK9' # leave blank if you don't want google analytics
disqus_short_name: # 'greeksharifa-github-io' # leave blank if you don't want disqus

comments:
  provider    : # "disqus"                                # comment 처리 사이트 명칭 기재
              # false (default), "disqus", "discourse", "facebook"
              # "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname : # "greeksharifa-github-io"                    # disqus의 shortname 기재

# Analytics
analytics:
  provider               : # "google-universal" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : # "G-7BD8CT32B0"
    anonymize_ip         : # true, false (default)